language: node_js
node_js:  
  - "node"
branches:
  only:
  - master
before_install:
   - export TZ=Asia/Kolkata
   - rvm install 2.6.5
cache:
  bundler: true
  node_modules: true
install:
- npm install
- gem update --system
- gem install jekyll -v 3.8.5
- gem install bundler -v 2.1.4 --user-install
- bundle install

script:
  - gulp build

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: gh-pages
  email: tksudharshan@gmail.com
  name: tks18
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master