# Site Settings
# Site Settings
title: Gadgets
tagline: Technically Dope
description: >-
  Gadget by Dope-T-Rope is a Spin-off from Dopetrope project particularly focusing on Gadget Reviews and its News.Dopetrope is a Project Found For Sharing Tech News and Updates from various Tech Sources and Blogs.The latest tech news about the world's best (and sometimes worst) hardware, apps, and much more. 
  From top companies like Google and Apple to tiny startups vying for your attention, Dopetrope has the latest in what matters in technology daily.
seotags:
  - Technology
  - Tech news
  - Gadget News
  - Tech Blog
  - Gadget Reviews
  - Creators News
show_hero: true
email: tksudharshan@infozy.tk
disqus_username: read-write-tech
paginate: 21
maintainer: Sudharshan TK


# Social Media Settings
github_username: tks18
twitter_username: shantk18
instagram_username: shantk18
medium_username: tksudharshan


# Theme Settings
themeColor: '#fa163f'
primaryDark: '#141414'
accentDark: '#ffffff'
lightGray: '#d8d8d8'
texts: '#333333'


# Posts Settings
show_time_bar: true
show_modal_on_exit: true
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gadgets.dopetrope.tk" # the base hostname & protocol for your site
google_analytics: "UA-156929545-1"
language: "en"


# Image Quality and CDN Settings
# CDN and Image Settings
cdn: https://cdn.statically.io/img/
image: gadgets.dopetrope.tk/assets/img/
height_thumbnail: 580
width_thumbnail: 920
height_post: 1080
width_post: 1920
auto_webp_conversion: true


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
  category:
    output: true
paginate_path: "/page/:num/"

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md',
  'personal-token.txt',
  '.npmrc',
  'LICENSE'
]

timezone: Asia/Kolkata