#-------------------------------
# General Site Settings

title: Tech-Bytes | Technology Bites
description: Tech-Bytes is a Simple Blog for Some Cool Tech Tips to Make your Life More Productive and More Usefull.  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech-bytes.tk" # the base hostname & protocol for your site, e.g. http://example.com
email: tksudharshan@gmail.com

#-------------------------------
# About Section
author-name:   Sudharshan TK
author-avatar: profile.jpeg


#-------------------------------
# Contact links
facebook:   
twitter:   https://twitter.com/shantk18 
instagram: https://www.instagram.com/shantk18 
pinterest:  


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: read-write-tech # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-----------------u --------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: https://gmail.us4.list-manage.com/subscribe/post?u=98556fb006c99e546c771ed9c&amp;id=53b6d6f1c6 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
