# CDN and Image Settings
cdn: https://cdn.statically.io/img/
image: gadgets.dopetrope.tk/assets/images/

# Thumbnail Quality Settings
height_thumbnail: 580
width_thumbnail: 920

# Main Post Image Quality Settings
height_post: 1080
width_post: 1920

# Auto Webp Conversion Based on Browser
auto_webp_conversion: true
