backend:
  name: git-gateway
  branch: master
media_library: img/
publish_mode: editorial_workflow
collections:
  - label: "Posts"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "Featured Image"
        name: "image"
        widget: "string"
        allow_multiple: false
        required: false
      - label: "Tags"
        name: "tags"
        hint: "Separate with commas. These will also be used as keywords for search engines."
        widget: "list"
      - label: "Paginate"
        name: "paginate"
        widget: "boolean"
        default: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Pages"
    name: "pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    extension: "md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/{{slug}}/"
      - label: "Body"
        name: "body"
        widget: "markdown"
